Revert "[Eina] Use Eina_Lock and not pthread. Fix compilation on Windows."
This reverts commit 61d2367bd6f7c12be7e04b58cbe1011971b7a0f2. (@63877)

Reverted due to the following build failure:

eina_main.c:117:16: error: conflicting types for ‘_eina_tracking_lock’
../../src/include/eina_inline_lock_posix.x:83:29: note: previous declaration of ‘_eina_tracking_lock’ was here
make[3]: *** [libeina_la-eina_main.lo] Error 1

_eina_tracking_lock is used for implementation of Eina_Locks, so cannot be an Eina_Lock

Signed-off-by: Mike McCormack <mj.mccormack@samsung.com>

git-svn-id: http://svn.enlightenment.org/svn/e/trunk/eina@63904 7cbeb6ba-43b4-40fd-8cce-4c39aea84d33