eina_error: improvements to make it faster.
Use a simple array instead of inlist, error get is now much faster
using direct index access.



git-svn-id: http://svn.enlightenment.org/svn/e/trunk/eina@42304 7cbeb6ba-43b4-40fd-8cce-4c39aea84d33