eina_error: deprecated old logging, move to eina_log.
git-svn-id: http://svn.enlightenment.org/svn/e/trunk/eina@42220 7cbeb6ba-43b4-40fd-8cce-4c39aea84d33